crossid/accessbot

app/auth.py, app/embeddings.py, app/llm/agents.py, app/llm/conversation.py, app/llm/model.py, app/llm/sql_chat_message_history.py, app/main.py, app/models.py, app/models_facade.py, app/models_facade_sql.py, app/routers/content.py, app/routers/internal.py, app/routers/org.py, app/routers/request.py, app/services.py, app/sql.py, app/tests/test_models_facade_sql.py, app/tests/test_vector_store.py
changes import statements to be relative
=> chore: change import statements

app/models_facade.py
adds return type to user store interface
=> fix: user store

app/main.py, poetry.lock
fix slack import in main file
fix lock file (demanded by poetry)
=> fix: slack

app/tests/test_create_user_store.py, app/tests/test_models_facade_sql.py, app/tests/test_vector_store.py
fixes most of the tests.
slack import still fails because of relative import
=> fix: test imports

app/user_store_factory.py
fixes imports in user store file
=> fix: imports

app/models_facade.py, app/models_facade_sql.py, app/routers/conversation.py
adds org_id as primary key to conversation and message tables.
closes #20
=> feat: org_id primary key

app/injector_extensions_module.py, app/injector_main_module.py
=> chore: relative imports

app/routers/conversation.py
get conversation should use the org's id, not the current_user.org_id
closes #39
=> fix: conversation router

app/routers/org.py, app/services.py, contrib/quickstart/quickstart.ipynb
=> feat: finished implementing wipe org

app/slack/__init__.py, app/slack/app.py, app/slack/event_app_home_opened.py, app/slack/event_message.py, app/tests/test_vector_store.py
=> fix: tests

app/models_facade_sql.py
=> refactor: rename tables to plural name

app/auth.py, app/injector_extensions_module.py, app/injector_main_module.py, app/llm/conversation.py, app/llm/prompts.py, app/llm/sql_chat_message_history.py, app/llm/tests/test_sql_chat_message_history.py, app/models_stores.py, app/models_stores_sql.py, app/routers/conversation.py, app/routers/internal.py, app/routers/org.py, app/services.py, app/slack/event_message.py, app/sql.py, app/tests/test_models_facade_sql.py, app/user_store_scim.py
=> Refactor facades -> stores

app/slack/router.py
hides slack endpoints from openapi schema
=> chore: hide slack endpoints

app/tests/test_vault_env_vars.py, app/vault_env_vars.py
vault should not hide exceptions
=> fix: vault impl

app/models.py, app/models_stores_sql.py
adds created_at to application model
=> fix: application model

app/llm/tools/create_ticket_for_role_request_tool.py, app/routers/conversation.py, app/routers/workspace.py, app/slack/event_message.py
Workspace: created_by
Conversation: assignee
resolved #87
=> fix: user should be email address rather token's sub

app/models.py, app/models_stores_sql.py
adds created_at attribute to workspace
closes #94
=> fix: workspace created_at

app/llm/tools/create_ticket/factory.py, app/llm/tools/create_ticket_for_role_request_tool.py
makes ticket system configuration optional
closes #98
=> fix: optional ticket system config

app/llm/graph.py, app/llm/nodes.py
fixes a couple of issue with the graph:
- recommender node should be able to return to DataOwner node
- entry point node should figure out the app_id even if the conversation is of the data_owner
=> fix: graph

app/routers/conversation.py, contrib/quickstart/quickstart.ipynb
adds a route to cancel a conversation.
closes #80
=> feat: cancel conversation

app/llm/tools/deny_access_tool.py, app/llm/tools/provision_role_tool.py
should let the data_owner node stream the tool answers
fixes #100
=> fix: provision tool

app/injector_main_module.py, app/models_stores.py, app/models_stores_sql.py, app/routers/workspace.py, app/services.py, app/tests/test_workspace_store_sql.py
deleting workspace must delete checkpoints
fixes #105
=> fix: delete workspace

app/models.py, app/models_stores_sql.py, app/routers/application.py
creates a partial application model to return from app store list and router
fixes #103
this also closes the issue crossid/accessbot-saas#15
=> fix: partial application model

app/evaluation/stores.py, app/json_file_stores.py, app/llm/tests/test_data_owner.py, app/models_stores.py, app/user_store_scim.py
adds add_user_to_workspace function to user_store interface
=> chore: user store api

app/evaluation/stores.py, app/evaluation/testing.py, app/llm/conversation.py, app/llm/nodes.py, app/llm/prompts.py, app/llm/tools/app_extra_intructions_tool.py, app/llm/tools/create_ticket_for_role_request_tool.py
changes prompts
fixes testing
if directory is not found, it most likely because the graph didn't use the recommender, so we return a message with a hint for self reflection
fixes #113
=> fix: better prompts

app/models.py
=> fix: field validator deprecation warning

app/llm/tools/create_ticket_for_role_request_tool.py, app/llm/tools/provision_role_tool.py
LLM should not treat the request as it's requested for the dataowner himself
fixes #120
=> fix: dataowner after approval msg

app/models_stores_sql.py, app/routers/application.py
Remove unnecessary DB queries that performs checks on the DB level if an instance exists
closes #92
=> chore: optimize db error handling

app/models_stores_sql.py, app/sql.py
fixes the create_tables function.
should only create the tables from metadata once.
=> fix: sql table creation

app/auth.py, app/authz.py, app/models.py, app/routers/application.py, app/routers/content.py, app/routers/conversation.py, app/routers/directories.py, app/routers/workspace.py
Implements route level authorization with scopes and admin check on the workspace.
closes #53
=> feat: authz scopes

app/models.py, app/models_stores_sql.py, app/routers/conversation.py, contrib/quickstart/quickstart.ipynb
- creates an index on conversation.status for better querying performance
- creates 2 router for archive/unarchive
closes #61
=> feat: archive conversation

app/llm/tools/create_ticket_for_role_request_tool.py, app/llm/tools/deny_access_tool.py, app/llm/tools/provision_role_tool.py, app/models.py, app/models_stores_sql.py
persist conversation summary after requesting access.
closes #111
=> feat: conversation summary

app/authz.py, app/injector_main_module.py, app/llm/prompts.py, app/llm/tests/test_rules_engine.py, app/llm/tests/test_tools.py, app/llm/tests/test_webhooks.py, app/llm/tools/access_data/factory.py, app/llm/tools/access_data/iface.py, app/llm/tools/access_data/mock.py, app/llm/tools/access_data/webhook.py, app/llm/tools/create_ticket_for_role_request_tool.py, app/llm/tools/rule_engine/rule_engine_agent.py, app/llm/tools/rule_engine/rule_engine_relevant_data.py, app/llm/tools/user_data/factory.py, app/llm/tools/user_data/iface.py, app/llm/tools/user_data/mock.py, app/llm/tools/user_data/webhook.py, app/llm/tools/utils.py, app/main.py, app/models.py, app/models_stores.py, app/models_stores_sql.py, app/routers/rule.py, app/services.py, app/utils/strings.py, docs/dev/api_exploration.ipynb
implements a rule engine llm agent
this runs before creating a ticket and decided if the request should be auto approved.
"approve" rules approve auto provisioning while "deny" rules explicitly deny auto provisioning.
closes #117
=> feat: rule engine llm

app/auth.py
fixes optional workspace function to not raise an error if workspace isn't found
closes #135
=> fix: optional workspace

app/authz.py, app/routers/workspace.py
adds a create:workspace scope to the list of scopes. 
changes needed scope to create workspace from update:workspace to create:workspace
=> chore: create workspace scope

app/ext_vector_store.py, app/routers/content.py, app/sql.py
fixes an issue where sql doc store points at the db uri instead of the vector store uri
fixes crossid/accessbot-saas#32
=> fix: sql doc store

app/routers/conversation.py, app/slack/event_message.py
=> fix: don't stream ended conversations

app/llm/tools/create_ticket_for_role_request_tool.py, app/llm/tools/provision_role_tool.py, app/llm/tools/utils.py
automatically approved requests should be in approved state.
closes #149
=> fix: auto approve request

app/llm/prompts.py
talk to the user in the same language he is using
closes #141
=> feat: same language

app/llm/tests/test_rules_engine.py, app/llm/tools/rule_engine/rule_engine_agent.py, app/models.py, app/models_stores_sql.py, docs/dev/api_exploration.ipynb, migrations/versions/75a1807159c8_adds_active_to_rules.py
adds active property to rules
closes #154
=> fix: rule active

app/i18n.py, app/llm/prompts.py, app/llm/tools/create_ticket/iface.py, app/llm/tools/create_ticket/slack.py, app/llm/tools/create_ticket_for_role_request_tool.py, app/llm/tools/utils.py
data owner conversation should be in the same language of the previous conversation. data owner message should be better formatted.
closes #155
=> feat: data owner conversation language

app/llm/agents.py, app/llm/guardrails/on_topic.py, app/llm/nodes.py, app/llm/prompts.py, app/llm/tools/rule_engine/rule_engine_agent.py, app/settings.py
move some llm calls to smaller llm models for better performance
closes #161 
closes #148
=> feat: small llm model

app/llm/guardrails/on_topic.py, app/llm/nodes.py
give the llm a larger context to work with.
be more specific about allowed topics
closes #166
=> fix: on topic guardrails

app/llm/guardrails/on_topic.py, app/llm/nodes.py
changes guardrail's prompt to take into consideration the conversation instead of just the latest message. changes the agent's messages to be AI to give the guardrail an opportunity to distinguish between user and ai messages correctly.
closes #180
=> fix: on topic guardrail

app/vector_store.py
create pgvector with a pre created engine instead of creating a new engine every time.
closes #186
=> fix: pgvector creation

app/data_fetching/factory.py, app/data_fetching/iface.py, app/data_fetching/mock.py, app/data_fetching/okta.py, app/data_fetching/utils.py, app/ext_vector_store.py, app/models.py, app/routers/directories.py, docs/dev/api_exploration.ipynb
create applications from while fetching okta groups
closes #185
=> feat: okta apps

app/data_fetching/factory.py, app/ext_vector_store.py, docs/dev/api_exploration.ipynb
when listing directory data, skips equal document, deletes non existent docs and insert new/changed docs.
closes #193
=> feat: skip equal docs

app/routers/directories.py
allows directory creation with configuration
closes #198
=> fix: create directory
